# Font size for the page title in typographic points
titleSize = 14

# Font size for the group titles in typographic points
groupTitleSize = 12

# Font size for item labels in typographic points
itemLabelSize = 7

# Page dimensions in millimetres, whole positive numbers
pageSize = {width = 148, height = 210}

# Marks the beginning of the page block
[[pages]]
# Page title, can be omitted
title = "First Page"

	# Marks the beginning of the group block
	[[pages.groups]]

	# Group title, required
	title = "Things"

	# Item dimensions in millimetres, whole positive numbers
	itemSize = {width = 120, height = 80}

	# Items in a group are entered with a multi-line string. This is based on the
	# assumption the most of the data comes from some kind of spreadsheet,
	# and allows simply copy-pasting from a CSV file. The required format is:
	#
	# Name used for the label, delimiter (either semicolon or tab character), path to the image file
	#
	# Note the triple apostrophes around `items` contents, making it a Multi-line literal string.
	# This allows using Windows paths with backslashes but means no escaping is performed!
	# In the output file the backslashes will be replaced with a forward slash.
	items = '''
This is an item label;C:\folder\image.png
Another item;D:\images\42.jpg
'''
	# Marks the beginning of the second group block
	[[pages.groups]]
	title = "Items"
	itemSize = {width = 75, height = 60}

	# Note the triple quotes for the multiline string this time.
	# This is an option that allows escaping inside the string.
	# Whitespace enclosing each field will be trimmed.
	# Here an escape sequence `\t` (tab character) is used for separating item fields.
	# Use the previous format!
	items = """
		item1 \t C:\\image1.png
		item2 \t C:\\image2.png
		item3 \t C:\\image3.png
	"""

# This is the start of the second page. The page title is omitted.
[[pages]]
	[[pages.groups]]
	title = "Other Things"
	itemSize = {width = 120, height = 40}
	items = '''
item4;C:\item4.png
item5;C:\item5.png
'''
